name: Process YouTube Video

# This allows you to run the workflow manually from the Actions tab in GitHub
on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'The full URL of the YouTube video to process'
        required: true
        type: string

jobs:
  build-and-process:
    runs-on: ubuntu-latest # Use a standard Linux runner

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m spacy download en_core_web_sm

    - name: Run the processing script
      env:
        # Use the secret you created in your repository settings
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        # Pass the user-provided URL as a command-line argument to your script
        python main.py "${{ github.event.inputs.video_url }}"

    - name: Upload results as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: processing-results
        path: |
          summary.json
          chroma_db/